use regex::Regex;

#[derive(Debug, Clone, PartialEq)]
pub enum LexerToken {
    Identifier(String),
    Const(i32),
    Int,
    Void,
    Return,
    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    Semicolon,
    Tilde,
    Hyphen,
    Decrement,
    Plus,
    Asterisk,
    ForwardSlash,
    Percent,
    Ampersand,
    Pipe,
    Caret,
    LeftShift,
    RightShift,
    ExclamationMark,
    TwoAmpersands,
    TwoPipes,
    TwoEqualSigns,
    ExclamationMarkEqualSign,
    LessThan,
    GreaterThan,
    LessThanOrEqual,
    GreaterThanOrEqual,
    // We need them to be able to remove them from code because we don't need them yet
    Comment,
    CompilerDirective,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum LexerTokenKind {
    Identifier,
    Const,
    Int,
    Void,
    Return,
    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    Semicolon,
    Tilde,
    Hyphen,
    Decrement,
    Plus,
    Asterisk,
    ForwardSlash,
    Percent,
    Ampersand,
    Pipe,
    Caret,
    LeftShift,
    RightShift,
    ExclamationMark,
    TwoAmpersands,
    TwoPipes,
    TwoEqualSigns,
    ExclamationMarkEqualSign,
    LessThan,
    GreaterThan,
    LessThanOrEqual,
    GreaterThanOrEqual,
    // We need them to be able to remove them from code because we don't need them yet
    Comment,
    CompilerDirective,
}

impl LexerToken {
    pub fn kind(&self) -> LexerTokenKind {
        match self {
            LexerToken::Identifier(_) => LexerTokenKind::Identifier,
            LexerToken::Const(_) => LexerTokenKind::Const,
            LexerToken::Int => LexerTokenKind::Int,
            LexerToken::Void => LexerTokenKind::Void,
            LexerToken::Return => LexerTokenKind::Return,
            LexerToken::OpenParen => LexerTokenKind::OpenParen,
            LexerToken::CloseParen => LexerTokenKind::CloseParen,
            LexerToken::OpenBrace => LexerTokenKind::OpenBrace,
            LexerToken::CloseBrace => LexerTokenKind::CloseBrace,
            LexerToken::Semicolon => LexerTokenKind::Semicolon,
            LexerToken::Tilde => LexerTokenKind::Tilde,
            LexerToken::Hyphen => LexerTokenKind::Hyphen,
            LexerToken::Decrement => LexerTokenKind::Decrement,
            LexerToken::Plus => LexerTokenKind::Plus,
            LexerToken::Asterisk => LexerTokenKind::Asterisk,
            LexerToken::ForwardSlash => LexerTokenKind::ForwardSlash,
            LexerToken::Percent => LexerTokenKind::Percent,
            LexerToken::Ampersand => LexerTokenKind::Ampersand,
            LexerToken::Pipe => LexerTokenKind::Pipe,
            LexerToken::Caret => LexerTokenKind::Caret,
            LexerToken::LeftShift => LexerTokenKind::LeftShift,
            LexerToken::RightShift => LexerTokenKind::RightShift,
            LexerToken::ExclamationMark => LexerTokenKind::ExclamationMark,
            LexerToken::TwoAmpersands => LexerTokenKind::TwoAmpersands,
            LexerToken::TwoPipes => LexerTokenKind::TwoPipes,
            LexerToken::TwoEqualSigns => LexerTokenKind::TwoEqualSigns,
            LexerToken::ExclamationMarkEqualSign => LexerTokenKind::ExclamationMarkEqualSign,
            LexerToken::LessThan => LexerTokenKind::LessThan,
            LexerToken::GreaterThan => LexerTokenKind::GreaterThan,
            LexerToken::LessThanOrEqual => LexerTokenKind::LessThanOrEqual,
            LexerToken::GreaterThanOrEqual => LexerTokenKind::GreaterThanOrEqual,
            // We need them to be able to remove them from code because we don't need them yet
            LexerToken::Comment => LexerTokenKind::Comment,
            LexerToken::CompilerDirective => LexerTokenKind::CompilerDirective,
        }
    }
}

impl LexerTokenKind {
    pub fn pattern(&self) -> Regex {
        Regex::new(match self {
            Self::Identifier => r"^[a-zA-Z_]\w*\b",
            Self::Const => r"^[0-9]+\b",
            Self::Int => r"^int\b",
            Self::Void => r"^void\b",
            Self::Return => r"^return\b",
            Self::OpenParen => r"^\(",
            Self::CloseParen => r"^\)",
            Self::OpenBrace => r"^\{",
            Self::CloseBrace => r"^\}",
            Self::Semicolon => r"^;",
            Self::Tilde => r"^~",
            Self::Hyphen => r"^-",
            Self::Decrement => r"^--",
            Self::Plus => r"^\+",
            Self::Asterisk => r"^\*",
            Self::ForwardSlash => r"^/",
            Self::Percent => r"^%",
            Self::Ampersand => r"^&",
            Self::Pipe => r"^\|",
            Self::Caret => r"^\^",
            Self::LeftShift => r"^<<",
            Self::RightShift => r"^>>",
            Self::ExclamationMark => r"^!",
            Self::TwoAmpersands => r"&&",
            Self::TwoPipes => r"\|\|",
            Self::TwoEqualSigns => r"==",
            Self::ExclamationMarkEqualSign => r"!=",
            Self::LessThan => r"<",
            Self::GreaterThan => r">",
            Self::LessThanOrEqual => r"<=",
            Self::GreaterThanOrEqual => r">=",
            // We need them to be able to remove them from code because we don't need them yet
            Self::Comment => r"^(?://[^\r\n]*|/\*[\s\S]*?\*/)",
            Self::CompilerDirective => r"(?m)^#[^\r\n]*",
        }).expect("Invalid regex")
    }

    pub fn token(&self, text: &str) -> LexerToken {
        match self {
            LexerTokenKind::Identifier => LexerToken::Identifier(text.to_string()),
            LexerTokenKind::Const => LexerToken::Const(text.parse().unwrap()),
            LexerTokenKind::Int => LexerToken::Int,
            LexerTokenKind::Void => LexerToken::Void,
            LexerTokenKind::Return => LexerToken::Return,
            LexerTokenKind::OpenParen => LexerToken::OpenParen,
            LexerTokenKind::CloseParen => LexerToken::CloseParen,
            LexerTokenKind::OpenBrace => LexerToken::OpenBrace,
            LexerTokenKind::CloseBrace => LexerToken::CloseBrace,
            LexerTokenKind::Semicolon => LexerToken::Semicolon,
            LexerTokenKind::Tilde => LexerToken::Tilde,
            LexerTokenKind::Hyphen => LexerToken::Hyphen,
            LexerTokenKind::Decrement => LexerToken::Decrement,
            LexerTokenKind::Plus => LexerToken::Plus,
            LexerTokenKind::Asterisk => LexerToken::Asterisk,
            LexerTokenKind::ForwardSlash => LexerToken::ForwardSlash,
            LexerTokenKind::Percent => LexerToken::Percent,
            LexerTokenKind::Ampersand => LexerToken::Ampersand,
            LexerTokenKind::Pipe => LexerToken::Pipe,
            LexerTokenKind::Caret => LexerToken::Caret,
            LexerTokenKind::LeftShift => LexerToken::LeftShift,
            LexerTokenKind::RightShift => LexerToken::RightShift,
            LexerTokenKind::ExclamationMark => LexerToken::ExclamationMark,
            LexerTokenKind::TwoAmpersands => LexerToken::TwoAmpersands,
            LexerTokenKind::TwoPipes => LexerToken::TwoPipes,
            LexerTokenKind::TwoEqualSigns => LexerToken::TwoEqualSigns,
            LexerTokenKind::ExclamationMarkEqualSign => LexerToken::ExclamationMarkEqualSign,
            LexerTokenKind::LessThan => LexerToken::LessThan,
            LexerTokenKind::GreaterThan => LexerToken::GreaterThan,
            LexerTokenKind::LessThanOrEqual => LexerToken::LessThanOrEqual,
            LexerTokenKind::GreaterThanOrEqual => LexerToken::GreaterThanOrEqual,
            // We need them to be able to remove them from code because we don't need them yet
            LexerTokenKind::Comment => LexerToken::Comment,
            LexerTokenKind::CompilerDirective => LexerToken::CompilerDirective,
        }
    }
}

pub const LEXER_TOKEN_KINDS: &[LexerTokenKind] = &[
    LexerTokenKind::Identifier,
    LexerTokenKind::Const,
    LexerTokenKind::Int,
    LexerTokenKind::Void,
    LexerTokenKind::Return,
    LexerTokenKind::OpenParen,
    LexerTokenKind::CloseParen,
    LexerTokenKind::OpenBrace,
    LexerTokenKind::CloseBrace,
    LexerTokenKind::Semicolon,
    LexerTokenKind::Tilde,
    LexerTokenKind::Hyphen,
    LexerTokenKind::Decrement,
    LexerTokenKind::Plus,
    LexerTokenKind::Asterisk,
    LexerTokenKind::ForwardSlash,
    LexerTokenKind::Percent,
    LexerTokenKind::Ampersand,
    LexerTokenKind::Pipe,
    LexerTokenKind::Caret,
    LexerTokenKind::LeftShift,
    LexerTokenKind::RightShift,
    LexerTokenKind::ExclamationMark,
    LexerTokenKind::TwoAmpersands,
    LexerTokenKind::TwoPipes,
    LexerTokenKind::TwoEqualSigns,
    LexerTokenKind::ExclamationMarkEqualSign,
    LexerTokenKind::LessThan,
    LexerTokenKind::GreaterThan,
    LexerTokenKind::LessThanOrEqual,
    LexerTokenKind::GreaterThanOrEqual,
    // We need them to be able to remove them from code because we don't need them yet
    LexerTokenKind::Comment,
    LexerTokenKind::CompilerDirective,
];

